document.write("<footer style='margin-top:30px;'>");
document.write("        <div class=\"container \">");
document.write("            <div class=\"row \">");
document.write("                <div class=\"col-md-3 col-md-offset-1 \" style=\"margin-top: 30px;color: white \">");
document.write("                    <h3>Contact Us<\/h3>");
document.write("                    <p>info@ivyprepschool.com");
document.write("                        <br> +1 (718) 261 4882 <\/p>");
document.write("                <\/div>");
document.write("                <div class=\"col-md-3 \" style=\"margin-top: 30px;color: white; \">");
document.write("                    <h3>Location<\/h3>");
document.write("                    <p>IvyPrep Forest Hills <br> 108-21 72nd Avenue <br> Forest Hills, NY 11375 <\/p>");
document.write("                <\/div>");
document.write("                <div class=\"col-md-4 \">");
document.write("                    <iframe src=\"https:\/\/www.google.com\/maps\/embed?pb=!1m18!1m12!1m3!1d3023.9046107676013!2d-73.844683685271!3d40.72011634505714!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c25e20adea812b%3A0xe0c48cb3d52ab7de!2s108-21+72nd+Ave%2C+Flushing%2C+NY+11375!5e0!3m2!1sen!2sus!4v1499541641837 \" width=\"100% \" height=\"200 \" frameborder=\"0 \" style=\"border:0;margin-top: 20px; \" allowfullscreen><\/iframe>");
document.write("                <\/div>");
document.write("            <\/div>");
document.write("            <div class=\"row \">");
document.write("                <div class=\"col-md-4 col-md-offset-4 \">");
document.write("                    <center>");
document.write("                        <img src=\"images\/ivyLogo.png \">");
document.write("                        <p>© 2017. All Rights Reserved.<\/p>");
document.write("                    <\/center>");
document.write("                <\/div>");
document.write("            <\/div>");
document.write("        <\/div>");
document.write("    <\/footer>");
document.write("<div id=\"footer\">");
document.write("        <div class=\"container col-xs-12 navbar-inverse navbar-fixed-bottom\" class=\"test1\">");
document.write("            <div class=\"row navBarRow\" id=\"bottomNav\">");
document.write("                <div class=\" custom text-center myBox\" style=\"display: inline-block;\"><a href=\"Services\/Classes.html\"><i class=\"glyphicon glyphicon-leaf\"><\/i><br><p>Programs<\/p><\/a> <\/div>");
document.write("                <div class=\"  custom text-center myBox\" style=\"display: inline-block;\"><a href=\"AboutUs.html\"><i class=\"glyphicon glyphicon-info-sign\"><\/i><br><p>About Us<\/p><\/a><\/div>");
document.write("                <div class=\" custom text-center myBox\" style=\"display: inline-block;\"><a href=\"Contact.html\"><i class=\"glyphicon glyphicon-earphone\"><\/i><br><p>Contact<\/p><\/a><\/div>");
document.write("                <div class=\" custom text-center myBox\" style=\"display: inline-block;\"><a href=\"Apply.html\"><i class=\"glyphicon glyphicon-pencil\"><\/i><br><p>Apply<\/p><\/a><\/div>");
document.write("");
document.write("            <\/div>");
document.write("        <\/div>");
document.write("    <\/div>");
