document.write("    <nav class=\"navbar navbar-inverse\" style=\"position: fixed; z-index: 2; width: 100%;\">");
document.write("        <div class=\"container\">");
document.write("            <!-- Brand and toggle get grouped for better mobile display -->");
document.write("            <div class=\"navbar-header\">");
document.write("                <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar-collapse-3\">");
document.write("                    <span class=\"sr-only\">Toggle navigation<\/span>");
document.write("                    <span class=\"icon-bar\"><\/span>");
document.write("                    <span class=\"icon-bar\"><\/span>");
document.write("                    <span class=\"icon-bar\"><\/span>");
document.write("                  <\/button>");
document.write("                <a class=\"navbar-brand hvr-grow\" href=\"..\/IvyPrep.html\" style=\"color: white;\">IvyPrep<\/a>");
document.write("            <\/div>");
document.write("");
document.write("            <!-- Collect the nav links, forms, and other content for toggling -->");
document.write("            <div class=\"collapse navbar-collapse \" id=\"navbar-collapse-3\">");
document.write("                <ul class=\"nav navbar-nav navbar-right \">");
document.write("                    <li class=\"hvr-highlight\"><a href=\"..\/IvyPrep.html\" style=\"color:white; \">Home<\/a><\/li>");
document.write("                    <li class=\"hvr-highlight\"><a href=\"..\/AboutUs.html\" style=\"color: white;\">About<\/a><\/li>");
document.write("                    <li class=\"dropdown hvr-highlight\">");
document.write("                        <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\" style=\"color: white;\">Services <span class=\"caret\"><\/span><\/a>");
document.write("                        <ul class=\"dropdown-menu\">");
document.write("                            <li><a href=\"..\/services\/Classes.html\">Classes<\/a><\/li>");
document.write("                            <li role=\"separator\" class=\"divider\"><\/li>");
document.write("                            <li><a href=\"..\/Services\/tutoring.html\">Private Tutoring<\/a><\/li>");
document.write("                            <li role=\"separator\" class=\"divider\"><\/li>");
document.write("                            <li class=\"dropdown-submenu\">");
document.write("                                <a tabindex=\"-1\">Tests<\/a>");
document.write("                                <ul class=\"dropdown-menu\">");
document.write("                                    <li><a href=\"sat.html\">SAT<\/a><\/li>");
document.write("                                    <li><a href=\"act.html\">ACT<\/a><\/li>");
document.write("                                    <li><a href=\"psat.html\">PSAT<\/a><\/li>");
document.write("                                    <li><a href=\"shsat.html\">SHSAT<\/a><\/li>");
document.write("                                    <li><a href=\"hunter.html\">HUNTER<\/a><\/li>");
document.write("                                    <li><a href=\"satsubject.html\">Sat Subject Tests<\/a><\/li>");
document.write("                                <\/ul>");
document.write("                            <\/li>");
document.write("                        <\/ul>");
document.write("                    <\/li>");
document.write("                    <li class=\"hvr-highlight\"><a href=\"..\/newsletter.html\" style=\"color: white;\">Events<\/a><\/li>");
document.write("                    <li class=\"hvr-highlight\"><a href=\"..\/Contact.html\" style=\"color: white;\">Contact<\/a><\/li>");
document.write("                    <li class=\"hvr-highlight\">");
document.write("                        <a href=\"..\/apply.html\" aria-expanded=\"false\" aria-controls=\"nav-collapse3\" style=\"color: white\">Apply<\/a>");
document.write("                    <\/li>");
document.write("                    <li class=\"hvr-highlight\"><a href=\"..\/loginForStu.html\" style=\"color: white;\">Contact<\/a><\/li>");
document.write("                <\/ul>");
document.write("");
document.write("            <\/div>");
document.write("            <!-- \/.navbar-collapse -->");
document.write("        <\/div>");
document.write("        <!-- \/.container -->");
document.write("    <\/nav>");
document.write("    <!-- \/.navbar -->");
document.write("    <div style=\"height: 52px;\"><\/div>");
